In [2]:
import pandas as pd
ventas=pd.read_csv(
    '/Users/HP/Documents/Data_Science/01-python-intro/ventas.csv',
    dtype={'precio_unitario':'float64'}
)    
ventas['importe']=ventas['unidades']*ventas['precio_unitario']
ventas

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,importe
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.00,650.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00,4480.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.00,280.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.00,12000.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10,260.0
...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45.0,0.00,180.0
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05,15600.0
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05,640.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.00,1920.0
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.00,360.0

In [4]:
ventas.groupby('region')['importe'].sum()

region
Centro    705695.0
Este      549745.0
Norte     862360.0
Oeste     626295.0
Sur       699920.0
Name: importe, dtype: float64

In [5]:
ventas[ventas['region']=='Sur']['importe'].sum()

np.float64(699920.0)

In [10]:
ventas.groupby('region')['importe'].agg(
    importe_total='sum',
    importe_promedio='mean',
    total_registros='count'
    )

        importe_total  importe_promedio  total_registros
region
Centro       705695.0       2594.466912              272
Este         549745.0       3054.138889              180
Norte        862360.0       2827.409836              305
Oeste        626295.0       3085.197044              203
Sur          699920.0       2916.333333              240

In [11]:
ventas.groupby('region').agg({
    'importe':['sum','mean','max'],
    'unidades':['sum'],
    'producto':['nunique']
})

         importe                       unidades producto
             sum         mean      max      sum  nunique
region
Centro  705695.0  2594.466912  15600.0     1933        8
Este    549745.0  3054.138889  16800.0     1384        8
Norte   862360.0  2827.409836  16800.0     2166        8
Oeste   626295.0  3085.197044  15600.0     1469        8
Sur     699920.0  2916.333333  16800.0     1779        8