In [1]:
import pandas as pd

In [4]:
ventas=pd.read_csv(
    '/Users/HP/Documents/Data_Science/01-python-intro/ventas.csv',
    dtype={'precio_unitario':'float64'}
)

In [5]:
ventas.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450.0,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280.0,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200.0,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450.0,0.0

In [ ]:
#mascara devuelve booleanos
mascara=ventas['region']=='Sur'
ventas_sur=ventas[mascara]
ventas_sur.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95.0,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280.0,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640.0,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10

In [ ]:
#asignar de frente la mascara
ventas[ventas['region']=='Sur']

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95.0,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130.0,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95.0,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95.0,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280.0,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640.0,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10

In [8]:
#Dos filtros a la vez
df_filtrado=ventas[(ventas['region']=='Sur')&(ventas['precio_unitario']>90)]
df_filtrado

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95.0,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130.0,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95.0,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95.0,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280.0,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640.0,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10

In [10]:
df_filtrado['precio_unitario'].unique()

array([], dtype=float64)

In [9]:
df_filtrado=ventas[(ventas['region']=='Sur')&(ventas['region']=='Norte')]
df_filtrado

Empty DataFrame
Columns: [fecha, region, vendedor, producto, categoria, unidades, precio_unitario, descuento]
Index: []

In [12]:
df_filtrado=ventas[(ventas['region']=='Sur')|(ventas['region']=='Norte')]
df_filtrado

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280.0,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.0
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320.0,0.1
...,...,...,...,...,...,...,...,...
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.0
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.1
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640.0,0.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.0
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.0

In [13]:
ventas[ventas['region']!='Sur']

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.00
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450.0,0.00
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280.0,0.00
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45.0,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.00

In [14]:
ventas[ventas['region'].isin(['Sur','Norte'])]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280.0,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.0
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320.0,0.1
...,...,...,...,...,...,...,...,...
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.0
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.1
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640.0,0.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.0
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.0

In [15]:
df_filtrado=ventas[ventas['precio_unitario'].between(90,200)]
df_filtrado

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
13,2024-01-05,Norte,Sofia Leon,Auriculares,Accesorios,11,130.0,0.00
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95.0,0.05
18,2024-01-06,Oeste,Carlos Vega,Auriculares,Accesorios,2,130.0,0.10
...,...,...,...,...,...,...,...,...
1173,2024-12-22,Norte,Marta Ruiz,Teclado Mec,Accesorios,12,95.0,0.05
1177,2024-12-24,Oeste,Ana Torres,Auriculares,Accesorios,11,130.0,0.00
1183,2024-12-26,Centro,Luis Gomez,Auriculares,Accesorios,6,130.0,0.00
1189,2024-12-29,Oeste,Javier Sanz,Auriculares,Accesorios,6,130.0,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10

In [17]:
#1
ventas['region'].value_counts()['Centro']
len(ventas[ventas['region']=='Centro'])

272

In [18]:
#2
ventas[(ventas['categoria']=='Tecnologia')&(ventas['unidades']>10)]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00
16,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200.0,0.00
27,2024-01-09,Este,Carlos Vega,Laptop Pro,Tecnologia,12,1200.0,0.00
40,2024-01-14,Centro,Marta Ruiz,Laptop Pro,Tecnologia,12,1200.0,0.10
89,2024-01-31,Centro,Sofia Leon,Monitor 27,Tecnologia,12,320.0,0.00
...,...,...,...,...,...,...,...,...
1174,2024-12-22,Norte,NaN,Laptop Pro,Tecnologia,14,1200.0,0.00
1176,2024-12-23,Centro,Carlos Vega,Monitor 27,Tecnologia,11,320.0,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640.0,0.00
1188,2024-12-28,Este,Luis Gomez,Tablet Air,Tecnologia,13,640.0,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05

In [19]:
#3
ventas[ventas['descuento']>0]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200.0,0.10
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320.0,0.10
11,2024-01-04,Oeste,Pedro Diaz,Escritorio,Mobiliario,10,450.0,0.05
12,2024-01-04,Centro,Marta Ruiz,Tablet Air,Tecnologia,2,640.0,0.15
...,...,...,...,...,...,...,...,...
1187,2024-12-28,Este,Ana Torres,Raton Ergo,Accesorios,8,45.0,0.05
1190,2024-12-29,Centro,Luis Gomez,Laptop Pro,Tecnologia,1,1200.0,0.10
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05

In [ ]:
#4
ventas[(ventas['region'].isin(['Norte','Sur']))&(ventas['producto'])

In [ ]:
#5
ventas['importe']=ventas['unidades']*ventas['precio_unitario']

ventas[ventas['importe']>5000].sort_values('importe').isin(['Norte','Sur']))&(ventas['producto'])